server:
  port: 8888
spring:
  jmx:
    enabled: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/babytun?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 10000ms

mybatis:
  mapper-locations: classpath:/mapper/*.xml


